"""empty message

Revision ID: 6d4e50467c5d
Revises: 62343dfa1da2
Create Date: 2018-10-30 22:40:14.526000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4e50467c5d'
down_revision = '62343dfa1da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='user')
    op.create_unique_constraint(None, 'user', ['tel'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('id', 'user', ['id'], unique=True)
    # ### end Alembic commands ###
