"""empty message

Revision ID: ddcd1d0f23ad
Revises: 11ab95059977
Create Date: 2018-11-15 22:04:50.576000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddcd1d0f23ad'
down_revision = '11ab95059977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'book_ibfk_2', 'book', type_='foreignkey')
    op.drop_column('book', 'question_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'book_ibfk_2', 'book', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
