"""empty message

Revision ID: f89c7e188f3d
Revises: ddcd1d0f23ad
Create Date: 2018-11-15 22:52:32.892000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89c7e188f3d'
down_revision = 'ddcd1d0f23ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'create_time')
    # ### end Alembic commands ###
